---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-metadata
spec:
  params:
    - name: SNAPSHOT
      type: string
  volumes:
    - name: shared-volume
      emptyDir: {}
  steps:
    - name: fetch-metadata
      image: alpine:3.14
      script: |
        echo "Test metadata for $(params.SNAPSHOT)" > /workspace/shared/metadata.txt
      volumeMounts:
        - name: shared-volume
          mountPath: /workspace/shared