apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: provision-cluster
spec:
  description: |
    An integration test that runs test-metadata, provisions an ephemeral Hypershift cluster, obtains a kubeconfig, and stores data in a shared volume.
  params:
    - description: Snapshot of the application
      name: SNAPSHOT
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
  volumes:
    - name: shared-volume
      emptyDir: {}

  tasks:
    - name: test-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/konflux-qe-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: common/tasks/test-metadata/0.1/test-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: test-name
          value: $(context.pipelineRun.name)
      volumeMounts:
        - name: shared-volume
          mountPath: /workspace/shared

    - name: provision-eaas-space
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
      params:
        - name: ownerName
          value: $(context.pipelineRun.name)
        - name: ownerUid
          value: $(context.pipelineRun.uid)
      volumeMounts:
        - name: shared-volume
          mountPath: /workspace/shared

    - name: provision-cluster
      runAfter:
        - test-metadata
        - provision-eaas-space
      taskSpec:
        volumes:
          - name: credentials
            emptyDir: {}
        steps:
          - name: get-supported-versions
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-supported-ephemeral-cluster-versions/0.1/eaas-get-supported-ephemeral-cluster-versions.yaml
            params:
              - name: eaasSpaceSecretRef
                value: /workspace/shared/secretRef.txt
            volumeMounts:
              - name: shared-volume
                mountPath: /workspace/shared

          - name: pick-version
            ref:
              resolver: git
              params:
                - name: url
                  value: https://github.com/konflux-ci/build-definitions.git
                - name: revision
                  value: main
                - name: pathInRepo
                  value: stepactions/eaas-get-latest-openshift-version-by-prefix/0.1/eaas-get-latest-openshift-version-by-prefix.yaml
            params:
              - name: prefix
                value: "$(cat /workspace/shared/supported-versions.txt | jq -r '.versions[0]')."
            volumeMounts:
              - name: shared-volume
                mountPath: /workspace/shared

  finally:
    - name: grab-artifacts-final
      taskSpec:
        steps:
          - name: gather-results
            image: golang:1.22
            volumeMounts:
              - name: shared-volume
                mountPath: /workspace/shared
            script: |
              # Access all accumulated results in shared volume for final actions
              ls -larth /workspace/shared
